### ISSUE TITLE
Add def methods without parentheses

### ISSUE THREAD

**Issue by pablox-cl** [pavlitsky/vscode-yard#1]
Just wondering if it's possible to include also methods without parentheses, like:

```rb
def some_method parameter_1 parameter_2
end
```

I was trying to add a test, but I'm getting this:

```
/usr/lib/electron/electron --debugBrkPluginHost=31500 --debugId=d56f2c9b-c651-4044-8458-069c1e343f5f /home/pablo/code/vscode/vscode-yard/src/test/project --extensionDevelopmentPath=/home/pablo/code/vscode/vscode-yard --extensionTestsPath=/home/pablo/code/vscode/vscode-yard/out/test 
Error launching app
Unable to find Electron app at /home/pablo/code/vscode/vscode-yard/src/test/project
Cannot find module '/home/pablo/code/vscode/vscode-yard/src/test/project'
```

What I did:
1. Clone the repo
2. `npm install`
3. Open the folder on VS Code
4. Debug sidebar
5. Extension tests
6. Little green arrow

Nevertheless, I'm not that familiarized with javascript/typescript, but I was going to give it a go.

**Comment by pavlitsky** [comment]
@pablox-cl thank you for your issue! Did you mean that in this case parameters not get documented like this?
```ruby
#
# <Description>
#
# <---- oops, missing two @param
#
# @return [<Type>] <description>
#
def some_method parameter_1, parameter_2
end
```

**Comment by pavlitsky** [comment]
I.e. documenting methods without parentheses should work itself but parameters missing in this case, right?

**Comment by pablox-cl** [comment]
Exactly, that's what I expected, but it didn't wokr. I tried to setup my machine to at least add the corresponding tests, but I can't make vscode work with the extensions.

**Comment by pavlitsky** [comment]
@pablox-cl Good catch, I'll fix it, thanks!

**Comment by pablox-cl** [comment]
Ok, I could finally setup vscode as a development environment! I started adding some tests, but the problem is that the it should duplicate almost every test :/. I'm not so sure if that's correct.

**Comment by pavlitsky** [comment]
I think a single test `src/test/project/method/without_parentheses.rb` and its expectation should be enough. It'll test ability to grab and parse such params. There's no need to multiple tests for all params variations.

**Comment by pablox-cl** [comment]
I understand. I'll give it a go.
