### ISSUE TITLE
Doesn't generate method documentation for methods that aren't alphanumeric

### ISSUE THREAD

**Issue by boc-tothefuture** [pavlitsky/vscode-yard#10]
Thanks for creating this plugin!

I have noticed that the plugin doesn't generate method documentation if the method isn't alphanumeric.  For example

```
def |(other)

end
```

If you ask the plugin to generate method documentation using the hotkey, nothing happens.

**Comment by pavlitsky** [comment]
@boc-tothefuture can you please double-check it? When I press the hotkey I get this method documented:
```ruby
  #
  # <Description>
  #
  # @param [<Type>] |other <description>
  #
  # @return [<Type>] <description>
  #
  def |(other)

  end
```

`|other` parameter name should be fixed though, but it works. I checked it on two different machines.

**Comment by ahangarha** [comment]
I can generate docs, too.

I think this issue is already resolved.
