### ISSUE TITLE
Please publish it in open-vsx.org

### ISSUE THREAD

**Issue by brodock** [pavlitsky/vscode-yard#11]
Open VSX Registry (https://open-vsx.org/) is a free and opensource registry for VSCode alternatives, like VSCodium and Eclipse Theia. 

You can learn about it here: https://www.eclipse.org/legal/open-vsx-registry-faq/#faq-1 (and why it exists)

You can also reach out documentation https://github.com/eclipse/openvsx/wiki and how to publish on the registry (it's very similar)

**Comment by pavlitsky** [comment]
Will do that. Thank you for letting me know about these alternatives.

**Comment by pavlitsky** [comment]
Done https://open-vsx.org/extension/pavlitsky/yard

**Comment by brodock** [comment]
It works. thank you very much
