### ISSUE TITLE
New template

### ISSUE THREAD

**Issue by ccmywish** [pavlitsky/vscode-yard#12]
Hi @pavlitsky

 Thanks for developing this cool plugin！👍❤️

I have some simple advice for the generated docstring template.

Now the template is:
```ruby
    #
    # <Description>
    #
    # @param [<Type>] arg1 <description>
    # @param [<Type>] arg2 <description>
    #
    # @return [<Type>] <description>
    #
    def hello(arg1, arg2)
```

But I think the template below is clearer.
```ruby
    # <Description>
    #
    # @param arg1 [<Type>] <description>
    # @param arg2 [<Type>] <description>
    #
    # @return [<Type>] <description>
    #
    def hello(arg1, arg2)
```
I'm sorry I don't have TypeScript skills to do it myself. So, could you please make a patch if you agree with the change?

**Comment by pavlitsky** [comment]
@ccmywish Hi! Thank you for kind words, I'm glad you found this plugin useful.
There are two settings to make a template look like you mentioned:
```ts
"yard.spacers.beforeDescription" // Prepend an empty line to descriptive texts
"yard.tags.paramNameBeforeType" // Print param name before its type (for example '@param username [String]')
```
You can set the first one to `false`, and the second to `true`. Please try to set them and tell me if it works for you.

**Comment by ccmywish** [comment]
Wow, I didn't notice the settings in README ...😓

The setting above works! This plugin is very customizable. Thank you! 🥰

**Comment by ahangarha** [comment]
@pavlitsky 

Based on the [official documenation](https://rubydoc.info/gems/yard/file/docs/Tags.md#param), the format should be as following:

`@param name [Types] description`

Isn't it better to output this template by default?

**Comment by pavlitsky** [comment]
@ahangarha Yes, it's better. The reason I didn't changed the default yet, is I needing to double-check if the new default will apply for existing users also. I don't want all of them to get the order changed silently after update, so need to take into account this somehow.
Thank you for the reminder, I'll try to resolve this.
