### ISSUE TITLE
Incorrect MacOs Keyboard Shortcut Documentation

### ISSUE THREAD

**Issue by GaryBer** [pavlitsky/vscode-yard#4]
README.MD file incorrectly shows "Cmd+Alt+Enter on macOS", There is no ALT key on a MacOS keyboard.

**Comment by pavlitsky** [comment]
@GaryBer Please let me know which notation would look more familiar for Mac users: `Option+Command+Enter` or `⌥⌘Enter` or maybe some other?

**Comment by pavlitsky** [comment]
Shortcut fixed, thank you!
