### ISSUE TITLE
Should the param name go before the type?

### ISSUE THREAD

**Issue by dleavitt** [pavlitsky/vscode-yard#9]
YARD documentation indicates the the parameter name goes _before_ the type:
https://www.rubydoc.info/gems/yard/file/docs/Tags.md#param

```ruby
# @param url [String] the URL of the page to download
# @param directory [String] the name of the directory to save to
def load_page(url, directory: 'pages') end
```

The snippet generated by this plugin looks like this, with the field names _after_ the type name:
```ruby
#
# <Description>
#
# @param [<Type>] url <description>
# @param [<Type>] directory <description>
#
# @return [<Type>] <description>
#
def load_page(url, directory: 'pages') end
```

I've seen both in the wild though I believe the former is preferred - should this be updated?

**Comment by pavlitsky** [comment]
@dleavitt I've added a setting for this. Please have a look https://github.com/pavlitsky/vscode-yard/issues/7#issuecomment-602278996.

**Comment by dleavitt** [comment]
Appears I entirely missed the fact that there was a README! Sorry about that + thanks for replying!
